services:
    email_errors.exception_listener:
        class: Sparklink\EmailErrorsBundle\EventListener\ExceptionListener
        tags:
            - { name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException" }
        arguments:
            - "@email_errors.exception_mailer"

    email_errors.exception_mailer:
        class: Sparklink\EmailErrorsBundle\ExceptionMailer\ExceptionMailer
        arguments:
            - !abstract "email service to use to send the email"
            - "@twig"
            - "%email_errors.from%"
            - "%email_errors.to%"
            - "%email_errors.subject%"
            - "%email_errors.ignored_exception_classes%"
